version: 2

models:
  - name: local_bike_brands
    description: "This model contains information about brands provided by users on their orders"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brands"
        tests:
            - unique
            - not_null

  - name: local_bike_categories
    description: "This model contains information about categories of products placed by users, including the name of the category"
    columns:
      - name: category_id
        description: "Primary key, unique categories."
        tests:
            - unique
            - not_null
            
  - name: local_bike_customers
    description: "This model contains information about each customers who made an order"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null
            
  - name: local_bike_order_items
    description: "This model contains information about items in an order, a new PK was created with the concat of order_item and item_id."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order_item: generated by concatenating order_id and item_id."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order to the corresponding order."
        tests:
          - relationships:
              name: FK_order_id_from_orders
              to: ref('local_bike_orders')
              field: order_id
      - name: product_id
        description: "Foreign key linking the product to the corresponding order."
        tests:
          - relationships:
              name: FK_product_id_from_products
              to: ref('local_bike_products')
              field: product_id

  - name: local_bike_orders
    description: "This model contains details of each order"
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null

  - name: local_bike_products
    description: "This model contains information about the products in a order."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: category_id
        description: "Foreign key linking the product to the corresponding category."
        tests:
          - relationships:
              name: FK_category_id_from_categories
              to: ref('local_bike_categories')
              field: category_id

      - name: brand_id
        description: "Foreign key linking the product to the corresponding brand."
        tests:
          - relationships:
              name: FK_brand_id_from_brands
              to: ref('local_bike_brands')
              field: brand_id

  - name: local_bike_staffs
    description: "This model contains staff information, including where their phone number and name."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff."
        tests:
            - unique
            - not_null
      - name: manager_id
        description: "Foreign key linking the manager to the corresponding staff."
        tests:
          - relationships:
              name: FK_manager_id_from_staff
              to: ref('local_bike_staffs')
              field: staff_id
  - name: local_bike_stocks
    description: "This model contains stocks information,including store_id and product_id"
    columns:
      - name: stocks_id
        description: "Primary key, unique identifier for each stocks_id concatenating store_id and product_id."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the stock to the corresponding store."
        tests:
          - relationships:
              name: FK_store_id_from_stores
              to: ref('local_bike_stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking the stock to the corresponding product."
        tests:
          - relationships:
              name: FK_product_id_from_products
              to: ref('local_bike_products')
              field: product_id
  - name: local_bike_stores
    description: "This model contains store information,including name and adress"
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store"
        tests:
            - unique
            - not_null